// <auto-generated />
namespace purse.domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewDb_V2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewDb_V2));
        
        string IMigrationMetadata.Id
        {
            get { return "201509192149362_NewDb_V2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
