// <auto-generated />
namespace purse.domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NewDB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewDB));
        
        string IMigrationMetadata.Id
        {
            get { return "201509192145225_NewDB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
